spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: zx110119
    driver-class-name: org.postgresql.Driver

  ssl:
    bundle:
      jks:
        messages-resource:
          key:
            alias: messages-resource-sample
            password: password
          keystore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12
          truststore:
            location: classpath:keystore.p12
            password: password
            type: PKCS12