logging:
  level:
    root: INFO
    org:
      springframework: INFO
      hibernate: INFO

spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: zx110119