server:
  port: 8761

spring:
  application:
    name: auth

  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    tags:
      application: ${spring.application.name}