server:
  port: 8762

spring:
  application:
    name: hypervisor
  profiles:
    active: dev

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  aop:
    proxy-target-class: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}