logging:
  level:
    root: INFO
    org:
      springframework: INFO

spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/leafage_hypervisor?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456