##=====log common=====##
logging:
  level:
    root: info
    org:
      springframework: info

spring:
  cloud:
    ##=====consul=====##
    consul:
      host: 127.0.0.1
      port: 8500

  ##=====mongodb config=====##
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: hypervisor
