logging:
  level:
    root: info
    org:
      springframework: info

spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 0000

  r2dbc:
    url: r2dbc:postgresql://postgres@localhost:5432
    username: postgres
    password: zx110119
    name: postgres