##=====log common=====##
logging:
  level:
    root: INFO
    org:
      springframework: INFO

spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 0000

  data:
    mongodb:
      host: 127.0.0.1
      port: 123456
      username: xxxx
      password: xxxx
      database: xxxx
      authentication-database: xxxx